import dotenv from "dotenv"
dotenv.config()
import { connectDB } from "../config/db.js"
import Booking from "../models/Booking.model.js"

const today = new Date("2025-10-14T12:00:00.000Z");

// Function to get a date relative to today
const getDate = (daysOffset) => {
  const date = new Date(today);
  date.setDate(date.getDate() + daysOffset);
  return date;
};

async function run() {
  await connectDB()
  await Booking.deleteMany({}) // reset

  const samples = [
     {
    customerName: "Priya Sharma",
    carDetails: { make: "Maruti Suzuki", model: "Swift", year: 2022, type: "hatchback" },
    serviceType: "Full Detailing",
    date: getDate(-4),
    timeSlot: "02:00 PM - 04:00 PM",
    duration: 120,
    price: 85.50,
    status: "Completed",
    rating: 5,
    review: "Excellent service! My car looks brand new. Very professional.",
    addOns: ["Wax Coating", "Tire Shine"],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Rohan Mehra",
    carDetails: { make: "Mercedes-Benz", model: "C-Class", year: 2024, type: "luxury" },
    serviceType: "Full Detailing",
    date: getDate(-22),
    timeSlot: "04:00 PM - 06:00 PM",
    duration: 120,
    price: 150.00,
    status: "Completed",
    rating: null,
    review: null,
    addOns: ["Leather Conditioning"],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Aditya Kumar",
    carDetails: { make: "Toyota", model: "Fortuner", year: 2023, type: "suv" },
    serviceType: "Deluxe Wash",
    date: getDate(-60),
    timeSlot: "12:00 PM - 01:00 PM",
    duration: 60,
    price: 50.00,
    status: "Completed",
    rating: 4,
    review: "Good job, but was a bit delayed.",
    addOns: [],
    isDeleted: true,
    deletedAt: getDate(-43),
  },
  {
    customerName: "Neha Reddy",
    carDetails: { make: "Kia", model: "Sonet", year: 2023, type: "suv" },
    serviceType: "Deluxe Wash",
    date: getDate(-10),
    timeSlot: "10:00 AM - 11:00 AM",
    duration: 60,
    price: 55.00,
    status: "Completed",
    rating: 5,
    review: "Quick and efficient service.",
    addOns: ["Interior Vacuum"],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Sameer Khan",
    carDetails: { make: "Mahindra", model: "XUV700", year: 2023, type: "suv" },
    serviceType: "Basic Wash",
    date: getDate(-30),
    timeSlot: "03:00 PM - 03:30 PM",
    duration: 30,
    price: 25.00,
    status: "Completed",
    rating: null,
    review: null,
    addOns: [],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Vivek Nair",
    carDetails: { make: "Volkswagen", model: "Polo", year: 2021, type: "hatchback" },
    serviceType: "Full Detailing",
    date: getDate(-8),
    timeSlot: "09:00 AM - 11:00 AM",
    duration: 120,
    price: 90.00,
    status: "Completed",
    rating: 4,
    review: "The detailing was thorough. Impressed with the results.",
    addOns: ["Engine Bay Cleaning"],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Divya Chawla",
    carDetails: { make: "Audi", model: "A4", year: 2024, type: "luxury" },
    serviceType: "Deluxe Wash",
    date: getDate(-12),
    timeSlot: "01:00 PM - 02:00 PM",
    duration: 60,
    price: 70.00,
    status: "Completed",
    rating: 5,
    review: "Always a pleasure. Top-notch service for my car.",
    addOns: ["Wax Coating"],
    isDeleted: false,
    deletedAt: null,
  },
   {
    customerName: "Geeta Choudhary",
    carDetails: { make: "Maruti Suzuki", model: "Ertiga", year: 2022, type: "suv" },
    serviceType: "Basic Wash",
    date: getDate(-5),
    timeSlot: "11:30 AM - 12:00 PM",
    duration: 30,
    price: 20.00,
    status: "Completed",
    rating: 3,
    review: "It was an okay wash, some spots were missed.",
    addOns: [],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Amit Khanna",
    carDetails: { make: "Skoda", model: "Kushaq", year: 2023, type: "suv" },
    serviceType: "Deluxe Wash",
    date: getDate(-18),
    timeSlot: "02:00 PM - 03:00 PM",
    duration: 60,
    price: 48.00,
    status: "Completed",
    rating: null,
    review: null,
    addOns: ["Tire Shine"],
    isDeleted: false,
    deletedAt: null,
  },

  // --- Confirmed Bookings (Upcoming) ---
  {
    customerName: "Arjun Verma",
    carDetails: { make: "Hyundai", model: "Creta", year: 2023, type: "suv" },
    serviceType: "Deluxe Wash",
    date: getDate(1),
    timeSlot: "11:00 AM - 12:00 PM",
    duration: 60,
    price: 45.00,
    status: "Confirmed",
    addOns: ["Interior Vacuum"],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Priyanka Patel",
    carDetails: { make: "Kia", model: "Seltos", year: 2023, type: "suv" },
    serviceType: "Basic Wash",
    date: getDate(4),
    timeSlot: "10:00 AM - 10:30 AM",
    duration: 30,
    price: 25.00,
    status: "Confirmed",
    addOns: ["Tire Shine"],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Anjali Desai",
    carDetails: { make: "Honda", model: "Amaze", year: 2022, type: "sedan" },
    serviceType: "Full Detailing",
    date: getDate(2),
    timeSlot: "12:00 PM - 02:00 PM",
    duration: 120,
    price: 100.00,
    status: "Confirmed",
    addOns: ["Leather Conditioning", "Wax Coating"],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Rahul Joshi",
    carDetails: { make: "Tata", model: "Harrier", year: 2023, type: "suv" },
    serviceType: "Deluxe Wash",
    date: getDate(3),
    timeSlot: "04:00 PM - 05:00 PM",
    duration: 60,
    price: 50.00,
    status: "Confirmed",
    addOns: [],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Tanvi Shah",
    carDetails: { make: "MG", model: "Hector", year: 2022, type: "suv" },
    serviceType: "Basic Wash",
    date: getDate(5),
    timeSlot: "09:00 AM - 09:30 AM",
    duration: 30,
    price: 22.00,
    status: "Confirmed",
    addOns: ["Tire Shine"],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Mohit Bansal",
    carDetails: { make: "Jeep", model: "Compass", year: 2022, type: "suv" },
    serviceType: "Deluxe Wash",
    date: getDate(6),
    timeSlot: "11:00 AM - 12:00 PM",
    duration: 60,
    price: 52.50,
    status: "Confirmed",
    addOns: ["Interior Vacuum"],
    isDeleted: false,
    deletedAt: null,
  },
   {
    customerName: "Meera Krishnan",
    carDetails: { make: "Hyundai", model: "i20", year: 2023, type: "hatchback" },
    serviceType: "Basic Wash",
    date: getDate(7),
    timeSlot: "01:00 PM - 01:30 PM",
    duration: 30,
    price: 25.00,
    status: "Confirmed",
    addOns: [],
    isDeleted: false,
    deletedAt: null,
  },

  // --- Pending Bookings ---
  {
    customerName: "Sanya Gupta",
    carDetails: { make: "Honda", model: "City", year: 2021, type: "sedan" },
    serviceType: "Basic Wash",
    date: getDate(0),
    timeSlot: "09:30 AM - 10:00 AM",
    duration: 30,
    price: 25.00,
    status: "Pending",
    addOns: [],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Karan Malhotra",
    carDetails: { make: "BMW", model: "X1", year: 2023, type: "luxury" },
    serviceType: "Full Detailing",
    date: getDate(10),
    timeSlot: "10:00 AM - 12:00 PM",
    duration: 120,
    price: 160.00,
    status: "Pending",
    addOns: ["Leather Conditioning"],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Sneha Iyer",
    carDetails: { make: "Renault", model: "Kiger", year: 2022, type: "suv" },
    serviceType: "Deluxe Wash",
    date: getDate(8),
    timeSlot: "03:30 PM - 04:30 PM",
    duration: 60,
    price: 40.00,
    status: "Pending",
    addOns: [],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Ishika Agarwal",
    carDetails: { make: "Tata", model: "Tiago", year: 2021, type: "hatchback" },
    serviceType: "Basic Wash",
    date: getDate(9),
    timeSlot: "12:30 PM - 01:00 PM",
    duration: 30,
    price: 20.00,
    status: "Pending",
    addOns: ["Tire Shine"],
    isDeleted: false,
    deletedAt: null,
  },
   {
    customerName: "Harsh Singh",
    carDetails: { make: "Mahindra", model: "Thar", year: 2024, type: "suv" },
    serviceType: "Deluxe Wash",
    date: getDate(12),
    timeSlot: "04:00 PM - 05:00 PM",
    duration: 60,
    price: 60.00,
    status: "Pending",
    addOns: ["Interior Vacuum"],
    isDeleted: false,
    deletedAt: null,
  },
  
  // --- Cancelled Bookings ---
  {
    customerName: "Vikram Singh",
    carDetails: { make: "Tata", model: "Nexon", year: 2022, type: "suv" },
    serviceType: "Deluxe Wash",
    date: getDate(-9),
    timeSlot: "01:00 PM - 02:00 PM",
    duration: 60,
    price: 40.00,
    status: "Cancelled",
    addOns: [],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Pooja Rao",
    carDetails: { make: "Hyundai", model: "Verna", year: 2023, type: "sedan" },
    serviceType: "Full Detailing",
    date: getDate(-15),
    timeSlot: "11:00 AM - 01:00 PM",
    duration: 120,
    price: 95.00,
    status: "Cancelled",
    addOns: ["Wax Coating"],
    isDeleted: false,
    deletedAt: null,
  },
  {
    customerName: "Kunal Tandon",
    carDetails: { make: "Toyota", model: "Innova Crysta", year: 2022, type: "suv" },
    serviceType: "Basic Wash",
    date: getDate(-3),
    timeSlot: "05:00 PM - 05:30 PM",
    duration: 30,
    price: 30.00,
    status: "Cancelled",
    addOns: [],
    isDeleted: false,
    deletedAt: null,
  },
    {
    customerName: "Deepak Prasad",
    carDetails: { make: "Ford", model: "EcoSport", year: 2020, type: "suv" },
    serviceType: "Basic Wash",
    date: getDate(-45),
    timeSlot: "10:00 AM - 10:30 AM",
    duration: 30,
    price: 25.00,
    status: "Completed",
    rating: null,
    review: null,
    addOns: [],
    isDeleted: true, // Soft-deleted
    deletedAt: getDate(-40),
  }
  ]

  await Booking.insertMany(samples)
  console.log("[seed] Inserted", samples.length, "bookings")
  process.exit(0)
}

run().catch((e) => {
  console.error(e)
  process.exit(1)
})
